apiVersion: v1
kind: Service
metadata:
  name: demo-app
spec:
  ports:
  - port: 80
    targetPort: 8080
  selector:
    app: demo-app
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo-app
  template:
    metadata:
      labels:
        app: demo-app
    spec:
      containers:
      - image: ghcr.io/rs324/demo-app:2cc225b9b1b993536aec5990b6f7dd1932747437
        name: demo-app
        ports:
        - containerPort: 8080
